### PR TITLE
General brushup

### PR DESCRIPTION
**Pull request by laborleben**
This PR includes lots of features:

- Cleanup of firmware
- Fix timing violations
- Adding FIFO readout interval
- Updating default parameters (e.g., use TLU DATA_FORMAT=2)
- Fixing lots of issues (e.g., config parser, ...)
- Adding support of 31 bit trigger number (TLU_TRIGGER_MAX_CLOCK_CYCLES=32)
- Removing TLU preempt request signal (M26 data now get immediately written to the FIFO output buffer)

TODO:
- [x] Discuss and test the removal of the TLU preempt request signal 
- [x] TLU tuning script (see https://github.com/SiLab-Bonn/pymosa/pull/11)
- [ ] Threshold tuning and noisy column masking (see https://github.com/SiLab-Bonn/pymosa/issues/10)
- [x] Testing firmware and software in September 2018 ELSA beam test (with TJMonopix)
- [x] Tune offset parameter in pymosa interpreter (for correlation) after FW is stable (see https://github.com/SiLab-Bonn/pyBAR_mimosa26_interpreter/pull/4)
- [x] Check/fix timestamp buffering in toplevel module
- [x] Adding support for IP address change
- [x] Support 100Mbps over RGMII (https://github.com/SiLab-Bonn/pymosa/commit/a43749c31b5c05f0781e0cf91e2469d450775e65)

The firmware (Version 7) and software was tested at the CERN SPS in May 2018.

### CODE REVIEW

**Comment by laborleben** [comment]
Right, ```reset()``` is not used. It was used for debugging -> @thirono

**Comment by laborleben** [comment]
@YannickDieter The threshold tuning and noisy column masking is still missing. Should we prepare a v1.0.0 release and the functionality later?

**Comment by YannickDieter** [comment]
We could think about this. At the moment I dont see an oportunity that I will manage to implement the M26 noise tuning this year. 
In addition I think pymosa is also without the noise tuning ready for a v1.0.0 release since many things were improved.

**Comment by laborleben** [comment]
We have to keep in mind that the M26 configuration files are only valid for the ANEMONE telescope planes.

**Pull request merged**
