### PR TITLE
Tuning and Online-Monitor

### PR DESCRIPTION
**Pull request by YannickDieter**
This PR adds:

- noise tuning and a noise occ. scan for Mimosa26 telescope.
- dedicated online monitor is now available with a 'generic' hit correlator (basically any DUT can now be correlated with each other).
- python3 support

Fixes issue #7, #18. 
Related to #12, #10.

### CODE REVIEW

**Comment by YannickDieter** [comment]
I dont know why travis status is not shown, but for Python3 travis passes. For python2 the unit tests for the online monitor fail. 
This is due to the fact that the Tabs (in the online monitor) for the Hit Correlator and DUT Receiver are at different positions when using python2 or python3. At the moment they are recognized by their index (see [here](https://github.com/SiLab-Bonn/pymosa/blob/enhancements/pymosa/tests/test_monitor.py#L167)), which makes it impossible to test it for both python versions at the same time.

@DavidLP Do you know more about that? The .yaml config file is stored on alphabetically order for both versions. In case of python3 the Tabs will be sorted in that way. For python2 it is the other way around.

**Comment by YannickDieter** [comment]
In principle I am done with that MR. 

One thing which needs to be discussed is, if we want to move the hit_correlator (which is now generic and can correlate DUTs from differnt input data streams) should be moved to our silab_online_monitor repo. In my opinion we should do that. What do you think? @laborleben @themperek  @DavidLP

**Comment by laborleben** [comment]
@YannickDieter One cannot rely on the sorting of a python dictionary. Here is why: https://portingguide.readthedocs.io/en/latest/dicts.html

**Comment by laborleben** [comment]
@DavidLP @YannickDieter Pushed a fix for the online-monitor addressing failing test: https://github.com/SiLab-Bonn/online_monitor/issues/17

**Comment by laborleben** [comment]
@YannickDieter Fixed.

**Comment by YannickDieter** [comment]
@laborleben Thanks for fixing that! I guess it is now finally ready to merge.

One more question: Why do your commits have a travis status, but my commits do not show any travis status?

**Comment by laborleben** [comment]
@YannickDieter Can you check the boxes of issue #10?

**Comment by YannickDieter** [comment]
So far only the local thresholds (A, B, C, D) are tuned. Nevertheless I would just merge it, I will add the missing features later. Unfortunately I could never really test the tuning during testbeam..

**Comment by laborleben** [comment]
@YannickDieter  @DavidLP Should we use this opportunity to update the pyBAR_mimosa26_interpreter package name?

**Comment by laborleben** [comment]
Github link for that: https://help.github.com/en/github/administering-a-repository/renaming-a-repository

**Comment by YannickDieter** [comment]
Yes, in my opinion we should do that! This is still on my ToD list.

**Pull request merged**
